# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('prenume', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('proiect', models.FileField(upload_to='proiecte/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nota', models.IntegerField(default=0)),
            ],
        ),
    ]
