services:
  fastapi:
    #image: dejanualex/fastapi:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    
  grafana:
    image: grafana/grafana-enterprise 
    ports:
      - "3000:3000"
    