apiVersion: rbac.authorization.k8s.io/v1
# this rolebiding applies to the default service account in the ns
kind: RoleBinding
metadata:
  name: hr-reader-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: hr-reader-role
  apiGroup: rbac.authorization.k8s.io
