apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hr-reader-rolebinding
  namespace: test1
subjects:
# this rolebiding applies to the default service account in the ns
- kind: ServiceAccount
  name: default
  namespace: test1
roleRef:
  kind: Role
  name: hr-reader-role
  apiGroup: rbac.authorization.k8s.io
