version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    container_name: flaskfrontend    
  redis:
    image: "redis:alpine"
    container_name: redisbackend
