apiVersion: batch/v1
kind: CronJob
metadata:
  name: helmclean
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: helmjanitor
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:  ["kubectl",  "get", "po"]
            #command:
            #- /bin/sh
            #- -c
            #- date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure