apiVersion: batch/v1
kind: Job
metadata:
  name: helmclean
  labels:
    sidecar.istio.io/inject: "false"
spec:
  template:
    spec:
      containers:
      - name: helmjanitor
        # image: bitnami/kubectl:latest
        image: dejanualex/kubectl:1.0
        command: ["kubectl",  "get", "po"]
      serviceAccountName: default
      restartPolicy: Never
  backoffLimit: 4